import java.lang.*;
import java.io.*;
class A
{
public static void main(String args[])
{
//exceptional handling

try
{
try
{
int arr[]={12,23,34};
arr[34]=33;
System.out.println("hrllo");
int a=12;
int b=0;
int c=a/b;
System.out.println(c);

}
catch(ArithmeticException ae)
{
System.out.println(ae);
}
}
catch(Exception ae)
{
System.out.println(ae);
}
System.out.println("hello this is the code which is running after the exception is handeled");
System.out.println("exceptional handling is very easy");
}
}
